package cn.edu.buaa.patpat.judge.dto;

import lombok.Data;

import java.time.LocalDateTime;

@Data
public class JudgeRequest {
    /**
     * Submission ID. This is generated by PatBoot.
     * Use this to determine the location of the submission.
     * /judge/{id}
     */
    private int id;

    /**
     * The ID of the problem.
     * Use this to determine the location of the problem.
     * /problem/{id}
     */
    private int problemId;

    /**
     * The Java version of the submission, e.g. 8, 11, 17.
     */
    private String language;

    private LocalDateTime submitTime;
    private LocalDateTime judgeTime;


    /**
     * The extra information of the submission, e.g. the user information.
     * As the judge doesn't need to know the user information, we use Object here.
     */
    private Object payload;
}
