judge:
  languages:
    - 17;E:\IDE\Java\jdk-17.0.5\bin
    - 20;E:\IDE\Java\jdk-20.0.2\bin
  problem-root: ../volume/bucket/problem
  submission-root: ../volume/bucket/submission
  sandbox-path: ../volume/bucket/sandbox
