spring:
  application:
    name: PatBoot
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
server:
  port: 8081
judge:
  problem-root: /problem
  submission-root: /submission
  sandbox-path: /sandbox
  timeout: 120
